version: '2'
services:

  red:
    build: .
    hostname: red
    command: tail -f /dev/null
    volumes:
      - ./bashrc:/root/.bashrc
      - ./inputrc:/root/.inputrc
      - ./tmux_red:/root/.tmux.conf
    environment:
      - TZ=Asia/Taipei

  blue:
    build: ./dockerdvwa
    hostname: blue
    command: /run.sh
    ports:
      - "8080:80"
    volumes:
      - ./bashrc:/root/.bashrc
      - ./inputrc:/root/.inputrc
      - ./tmux_blue:/root/.tmux.conf
      - ./snort_web.conf:/etc/snort/snort.conf
    environment:
      - TZ=Asia/Taipei
      - MYSQL_PASS="MYSQLPW"

  blue2:
    build: .
    hostname: blue2
    command: tail -f /dev/null
    volumes:
      - ./bashrc:/root/.bashrc
      - ./inputrc:/root/.inputrc
      - ./tmux_blue:/root/.tmux.conf
      - ./snort_web.conf:/etc/snort/snort.conf
      - ./sshd_config:/etc/ssh/sshd_config
    environment:
      - TZ=Asia/Taipei



